src/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SubTask__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Estimate__c</fullName>
        <label>Estimate</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>To Do</fullName>
                    <default>true</default>
                    <label>To Do</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Done</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TaskCard__c</fullName>
        <label>TaskCard</label>
        <referenceTo>TaskCard__c</referenceTo>
        <relationshipLabel>SubTask</relationshipLabel>
        <relationshipName>SubTask</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TotalTrack__c</fullName>
        <label>TotalTrack</label>
        <summarizedField>TrackTime__c.Time__c</summarizedField>
        <summaryForeignKey>TrackTime__c.SubTask__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>SubTask</label>
    <nameField>
        <label>SubTask Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubTask</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TaskCard__c.object
<CustomObject>
    <fields>
        <fullName>Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Estimate__c</fullName>
        <label>Estimate</label>
        <summarizedField>SubTask__c.Estimate__c</summarizedField>
        <summaryForeignKey>SubTask__c.TaskCard__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sprint_Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sprint Project</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Sprint__c.Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.Project__c</valueField>
            </filterItems>
            <filterItems>
                <field>Sprint__c.Status__c</field>
                <operation>notEqual</operation>
                <value>Closed</value>
            </filterItems>
            <filterItems>
                <field>Sprint__c.Status__c</field>
                <operation>notEqual</operation>
                <value>Complete</value>
            </filterItems>
            <infoMessage>Lol</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Sprint__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Task_Name__c</fullName>
        <label>Task Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <label>Total</label>
        <summarizedField>SubTask__c.TotalTrack__c</summarizedField>
        <summaryForeignKey>SubTask__c.TaskCard__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Feature</fullName>
                </value>
                <value>
                    <fullName>Bug</fullName>
                </value>
                <value>
                    <fullName>Spire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>TaskCard</label>
    <nameField>
        <displayFormat>TN-{00000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <recordTypes>
        <fullName>BackLog</fullName>
        <active>true</active>
        <label>BackLog</label>
    </recordTypes>
    <recordTypes>
        <fullName>Sprint</fullName>
        <active>true</active>
        <label>Sprint</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TaskCardController.cls
/**
 * Created by Ivan Basenko on 23.10.2018.
 */

public with sharing class TaskCardController {
    @AuraEnabled
    public static List<TaskCard__c> getBacklogTaskCard(Id id) {
        Id backlogId = getBacklogTypeId();
        return [SELECT Id,Name,Task_Name__c, Description__c,Sprint_Project__c,Estimate__c,RecordTypeId FROM TaskCard__c WHERE RecordTypeId = :backlogId AND Project__c = :id];
    }
    @AuraEnabled
    public static Id getBacklogTypeId() {
        return Schema.SObjectType.TaskCard__c.getRecordTypeInfosByName().get('BackLog').getRecordTypeId();
    }
    @AuraEnabled
    public static Id getSprintTypeId() {
        return Schema.SObjectType.TaskCard__c.getRecordTypeInfosByName().get('Sprint').getRecordTypeId();
    }

    @AuraEnabled
    public static void deleteTask(Id id) {
        Database.delete(id);
    }

    @AuraEnabled
    public static String cloneTask(List<Id> sprintTaskIds, List<Id> backlogTaskIds, Id currentSprintId) {
        Set<Id> allUnCompletedTaskIds = new Set<Id>(sprintTaskIds);
        System.debug(currentSprintId);
        allUnCompletedTaskIds.addAll(backlogTaskIds);
        List<TaskCard__c> originalTasks = [
                SELECT
                        Assignee__c,
                        Description__c,
                        Estimate__c,
                        Id,
                        Name,
                        OwnerId,
                        Project__c,
                        RecordTypeId,
                        Sprint_Project__c,
                        Stage__c,
                        Task_Name__c,
                        Total__c,
                        Type__c, (
                        SELECT
                                Description__c,
                                Estimate__c,
                                Id,
                                Name,
                                Status__c,
                                TaskCard__c,
                                TotalTrack__c
                        FROM SubTask__r
                )
                FROM TaskCard__c
                WHERE Id IN :allUnCompletedTaskIds
        ];
        List<TaskCard__c> tasksToBacklog = new List<TaskCard__c>();
        List<TaskCard__c> tasksToNewSprint = new List<TaskCard__c>();
        List<TaskCard__c> tasksToInsert = new List<TaskCard__c>();
        for (TaskCard__c taskCard : originalTasks) {
            TaskCard__c cloneTaskCard = taskCard.clone(false, true, true, false);
            if (backlogTaskIds.contains(taskCard.Id)) {
                cloneTaskCard.Assignee__c = null;
                cloneTaskCard.RecordTypeId = getBacklogTypeId();
                cloneTaskCard.Sprint_Project__c = null;
            } else {
                cloneTaskCard.Sprint_Project__c = currentSprintId;
            }
            cloneTaskCard.Stage__c = 'New';
            tasksToInsert.add(cloneTaskCard);
        }
        insert tasksToInsert;
        List<SubTask__c> subTasksToInsert = new List<SubTask__c>();
        for (TaskCard__c taskCard : tasksToInsert) {
            for (SubTask__c subTask : taskCard.SubTask__r) {
                SubTask__c cloneSubTask = subTask.clone(false, true, true, false);
                cloneSubTask.TaskCard__c = taskCard.Id;
                cloneSubTask.Estimate__c = cloneSubTask.Estimate__c - cloneSubTask.TotalTrack__c;
                cloneSubTask.Status__c = 'To Do';
                subTasksToInsert.add(cloneSubTask);
            }
        }
        insert subTasksToInsert;

        Set<Id> insertedTaskIds = (new Map<Id, SObject>(tasksToInsert)).keySet();
        List<TaskCard__c> cloneTask = [
                SELECT
                        Assignee__c,
                        Description__c,
                        Estimate__c,
                        Id,
                        Name,
                        OwnerId,
                        Project__c,
                        RecordTypeId,
                        Sprint_Project__c,
                        Stage__c,
                        Task_Name__c,
                        Total__c,
                        Type__c, (
                        SELECT
                                Description__c,
                                Estimate__c,
                                Id,
                                Name,
                                Status__c,
                                TaskCard__c,
                                TotalTrack__c
                        FROM SubTask__r
                )
                FROM TaskCard__c
                WHERE Id IN :insertedTaskIds
        ];

        for (TaskCard__c taskCard : cloneTask) {
            if (taskCard.Sprint_Project__c == null) {
                tasksToBacklog.add(taskCard);
            } else {
                tasksToNewSprint.add(taskCard);
            }
        }

        JSONGenerator jsonGen = JSON.createGenerator(true);
        jsonGen.writeStartObject();
        jsonGen.writeObjectField('taskToNewSprint', tasksToNewSprint);
        jsonGen.writeObjectField('taskToBacklog', tasksToBacklog);
        jsonGen.writeEndObject();
        return jsonGen.getAsString();
    }
}