src/objects/Sprint__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sprint_Start_Date__c</fullName>
        <label>Sprint Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Weeks__c</fullName>
        <label>Weeks</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SprintProjectController.cls
/**
 * Created by Ivan Basenko on 07.11.2018.
 */

public with sharing class SprintProjectController {
    @AuraEnabled
    public static void startSprint(Id id) {
        List<Sprint__c> sprints = [
                SELECT
                        End_Date__c,
                        Hours__c,
                        Id,
                        Name,
                        Sprint_Start_Date__c,
                        Status__c,
                        Weeks__c
                FROM Sprint__c
                WHERE Id = :id
        ];
        Sprint__c sprintProject = sprints.get(0);
        Integer weeks = Integer.valueOf(sprintProject.Weeks__c);
        if (sprintProject.Sprint_Start_Date__c == null) {
            sprintProject.Sprint_Start_Date__c = Date.today();
            sprintProject.End_Date__c = Date.today().addDays(weeks * 7);
        } else {
            sprintProject.End_Date__c = sprintProject.Sprint_Start_Date__c.addDays(weeks * 7);
        }
        sprintProject.Hours__c = 40 * weeks;
        sprintProject.Status__c = 'In Progress';
        update sprintProject;
    }

    @AuraEnabled
    public static List<User> checkEstimateForUser(String tasks, String weeks) {
        Integer week = Integer.valueOf(weeks);
        Integer hours = week * 40;

        List<Object> taskCards = (List<Object>) JSON.deserializeUntyped(tasks);
        System.debug(taskCards);
        Map<Id, Integer> userEstimateMap = new Map<Id, Integer>();
        for (Object o : taskCards) {
            Map<String, Object> data = (Map<String, Object>) o;
            Id userID = (Id) data.get('Assignee__c');
            Integer estimate = (Integer) data.get('Estimate__c');
            if (userEstimateMap.get(userID) != null) {
                estimate += userEstimateMap.get(userID);
            }
            userEstimateMap.put(userID, estimate);
        }

        Set<Id> userIdsWhereEstimateBiggestThenSprintHours = new Set<Id>();
        for (Id id : userEstimateMap.keySet()) {
            if (userEstimateMap.get(id) > hours) {
                userIdsWhereEstimateBiggestThenSprintHours.add(id);
            }
        }
        return [
                SELECT
                        Name
                FROM User
                WHERE Id IN :userIdsWhereEstimateBiggestThenSprintHours
        ];
    }
}