src/objects/Sprint__c.object
<CustomObject>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SubTask__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Estimate__c</fullName>
        <label>Estimate</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TaskCard__c</fullName>
        <label>TaskCard</label>
        <referenceTo>TaskCard__c</referenceTo>
        <relationshipLabel>SubTask</relationshipLabel>
        <relationshipName>SubTask</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TotalTrack__c</fullName>
        <label>TotalTrack</label>
        <summarizedField>TrackTime__c.Time__c</summarizedField>
        <summaryForeignKey>TrackTime__c.SubTask__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>SubTask</label>
    <nameField>
        <label>SubTask Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubTask</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TaskCard__c.object
<CustomObject>
    <fields>
        <fullName>Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Estimate__c</fullName>
        <label>Estimate</label>
        <summarizedField>SubTask__c.Estimate__c</summarizedField>
        <summaryForeignKey>SubTask__c.TaskCard__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Sprint_Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sprint Project</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Sprint__c.Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.Project__c</valueField>
            </filterItems>
            <filterItems>
                <field>Sprint__c.Status__c</field>
                <operation>notEqual</operation>
                <value>Closed</value>
            </filterItems>
            <filterItems>
                <field>Sprint__c.Status__c</field>
                <operation>notEqual</operation>
                <value>Complete</value>
            </filterItems>
            <infoMessage>Lol</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Sprint__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Task_Name__c</fullName>
        <label>Task Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>TaskCard</label>
    <nameField>
        <displayFormat>TN-{00000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TrackTime__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SubTask__c</fullName>
        <label>SubTask</label>
        <referenceTo>SubTask__c</referenceTo>
        <relationshipLabel>TrackTime</relationshipLabel>
        <relationshipName>TrackTime</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <label>Time</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>TrackTime</label>
    <nameField>
        <displayFormat>TT-{00000}</displayFormat>
        <label>TrackTime Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TrackTime</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SubTaskController.cls
/**
 * Created by Ivan Basenko on 25.10.2018.
 */

public with sharing class SubTaskController {
    @AuraEnabled
    public static List<SubTask__c> getSubTasksByTaskId(Id id) {
        return [
                SELECT
                        Description__c,
                        Estimate__c,
                        Id,
                        Name,
                        TotalTrack__c
                FROM SubTask__c
                WHERE TaskCard__c = :id
        ];
    }
    @AuraEnabled
    public static List<TrackTime__c> getTrackTimesBySubTaskId(Id id) {
        return [
                SELECT
                        Id,
                        Time__c,
                        Name,
                        Description__c
                FROM TrackTime__c
                WHERE SubTask__c = :id
        ];
    }
    @AuraEnabled
    public static String checkEstimateForUser(Id taskId) {
        TaskCard__c taskCard = [
                SELECT Id,
                        Assignee__c,
                        Estimate__c,
                        Sprint_Project__r.Hours__c,
                        Sprint_Project__c
                FROM TaskCard__c
                WHERE Id = :taskId
        ];
        List<TaskCard__c> taskCards = [
                SELECT
                        Assignee__c,
                        Estimate__c,
                        Id,
                        Name,
                        Task_Name__c
                FROM TaskCard__c
                WHERE Sprint_Project__c = :taskCard.Sprint_Project__c
                AND Assignee__c = :taskCard.Assignee__c
        ];
        Decimal totalEstimateForUser = 0;
        if (!taskCards.isEmpty()) {
            for (TaskCard__c card : taskCards) {
                totalEstimateForUser += card.Estimate__c;
            }
        }
        JSONGenerator jsonGen = JSON.createGenerator(true);
        jsonGen.writeStartObject();
        jsonGen.writeNumberField('totalEstimateForUser', totalEstimateForUser);
        jsonGen.writeNumberField('sprintEstimate', taskCard.Sprint_Project__r.Hours__c);
        jsonGen.writeEndObject();
        return jsonGen.getAsString();
    }
    @AuraEnabled
    public static void deleteById(Id id) {
        Database.delete(id);
    }
}